inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true
